### ISSUE TITLE
Exam-01 Question 8 

### ISSUE THREAD

**Issue by demar01** [rstudio-education/datascience-box#107]
Hi Mine,

Thanks so much for sharing this fantastic new edition of DSbox!

I am going through exam 1 and in question 8 when I try to recreate the plot I get some hits for origin EWR and dest PHL. I cannot get my head around why that facet is empty in the example. 
The code I am using to recreate the plot is:

flights %>% 
  filter(dest %in% c("PHL","RDU")) %>% 
  mutate(
    Arrival= case_when(
            arr_delay <= 0 ~ "ontime",
            TRUE ~ "delayed")) %>% 
          ggplot(aes(x=Arrival, y= dep_delay, color=dest))+
  geom_boxplot()+
  facet_grid(dest~origin)+
  labs(title="On time performance of NYC fligths",
       subtitle="December 2013",
  y="Departure delay", 
        color = "Destination")+
   coord_cartesian( ylim = c(0,200))

**Comment by debbieyuster** [comment]
Hi @demar01, it looks like your dataset is not filtered for December flights only.

**Comment by demar01** [comment]
Hi @debbieyuster 

That was exactly the issue. Updated code below. Thanks so much!

flights %>% 
  filter(dest %in% c("PHL","RDU")) %>% 
  filter(month==12) %>% 
  mutate(
    Arrival= case_when(
            arr_delay <= 0 ~ "ontime",
            arr_delay > 0 ~ "delayed")) %>% 
  filter(!is.na(Arrival)) %>% 
          ggplot(aes(x=Arrival, y= dep_delay, color=dest))+
  geom_boxplot()+
  facet_grid(dest~origin)+
  labs(title="On time performance of NYC fligths",
       subtitle="December 2013",
  y="Departure delay", 
        color = "Destination")+
   coord_cartesian( ylim = c(0,200))
