### ISSUE TITLE
Slide titles are broken after commit 76b505c

### ISSUE THREAD

**Issue by lukas-jue** [rstudio-education/datascience-box#116]
Thanks for providing these fantastic resources. I'm a big fan of this project!

It appears that commit 76b505cc731eae3b718821d8ece8ece73a5e9d03 broke the title headings for the slides.
After the commit, the file `datascience-box/course-materials/slides/setup.Rmd` includes 
```
::: {.my-footer}
<a href="https://introds.org" target="_blank">introds.org</a>
:::

------------------------------------------------------------------------
```
which produces this broken header in the knitted HTML slide:

![image](https://user-images.githubusercontent.com/49363975/112669857-7b34e200-8e60-11eb-9d0d-d83b645f55b8.png)

Replacing the code chunk above with
```
<div class="my-footer">
<span>
<a href="https://introds.org" target="_blank">introds.org</a>
</span>
</div>

---
```
as it was before commit 76b505cc731eae3b718821d8ece8ece73a5e9d03 fixes the issue.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, should be fixed now. The slides might take a few to re-render.
