### ISSUE TITLE
Help: Instructions for setting up hosting and building of course materials

### ISSUE THREAD

**Issue by graySquirrel** [rstudio-education/datascience-box#133]
Hi. I'm trying to figure out how to host all the course materials html files, as well as the 'book'.  I've poked through the github actions, but haven't really figured out how it all fits together.  

questions:
1) the 'book'  (datasciencebox.org or introds.org) is a website, but the coursematerials aren't directly accessible, though there are links to it (e.g. https://datasciencebox.org/hello-world.html points to https://rstudio-education.github.io/datascience-box/course-materials/slides/u1-d01-welcome/u1-d01-welcome.html#1).  Are these completely separate hosting sites?  I think so.
2) I goofed around with the github pages and got the 'book' hosted on github.io (though I think its wrong), but I can't figure out how to host the course materials.  Are there directions for that?  
3) I've seen the github actions, but i dont understand how that works.  There seems to be some references to Netlify, but then in other places, there are references to github pages.

Any clues on how to approach this would be greatly appreciated.
thx!

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the questions!

I've updated the site structure so the answers might differ from when you asked them.

1. They used to be, but now they're all hosted together.
2. Turning on GitHub Pages for your repo should work for both, but it would be difficult for me to answer precisely without seeing your setup.
3. Here is a neat writeup of GitHub actions for R users that might be helpful for getting started: https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/.
