### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by mlsp8727** [rstudio-education/datascience-box#140]
I cannot open the slide of Week 02-05-Visualizing categorical data.

https://github.com/rstudio-education/datascience-box/tree/main/course-materials/slides/u2-d04-viz-cat

**Comment by mine-cetinkaya-rundel** [comment]
It's at https://datasciencebox.org/course-materials/_slides/u2-d04-viz-cat/u2-d04-viz-cat.html#1.

If you can let me know where you came across the link, I'd be happy to update it!
