### ISSUE TITLE
Incorrect/dead link for tutorial 3 on interactive tutorials page.

### ISSUE THREAD

**Issue by UnitCircle** [rstudio-education/datascience-box#143]
On the [interactive tutorials page](https://datasciencebox.org/02-interactive-tutorials.html) the link for [Tutorial 3](https://minecr.shinyapps.io/dsbox-03-collegegrads/) generates this error:

This minecr.shinyapps.io page can’t be foundNo webpage was found for the web address: https://minecr.shinyapps.io/dsbox-03-collegegrads/
HTTP ERROR 404

I've confirmed that the links for [tutorial 2](https://minecr.shinyapps.io/dsbox-02-accidents/) and [tutorial 4](https://minecr.shinyapps.io/dsbox-04-legosales/) are both working fine.

**Comment by batpigandme** [comment]
Correct link appears to be https://minecr.shinyapps.io/dsbox-03-collegemajors/

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, the link is fixed now!
