### ISSUE TITLE
Link to RStudio workspace with student materials does not work

### ISSUE THREAD

**Issue by davidkane9** [rstudio-education/datascience-box#44]
From this paragraph

> All student facing materials for this course have been organized in an RStudio Cloud workspace here. Soon you will have the option to copy that workspace and use it to organize assignments and assessments.

The link in here (https://rstudio.cloud/spaces/1655/projects) give me a "Sorry, but you do not have access." message.

**Comment by mine-cetinkaya-rundel** [comment]
Link is now updated at https://datasciencebox.org/infrastructure/rscloud/ and should be working: https://rstudio.cloud/spaces/1655/join?access_code=6fbqA1UcHm0rLmdhjyQahLIBzMy%2FNt0P4Wmlx1TG. 

Workspace copying isn't yet available for RStudio Cloud, but I'm told it is in the horizon for the development team, so I'll be adding the rest of the content to the workspace.
