### ISSUE TITLE
Video linked in u2_d07-sim-test slides

### ISSUE THREAD

**Issue by matackett** [rstudio-education/datascience-box#55]
The Youtube video of the  Mythbusters experiment (linked on line 483 of the u2_d07-sim-test slides) is choppy; I think it has changed since these notes were originally created.

Here is a good video from the Discovery Channel website that explains the yawning experiment that the data are from.

https://www.discovery.com/tv-shows/mythbusters/videos/is-yawning-contagious-2

**Comment by mine-cetinkaya-rundel** [comment]
Thanks!
