### ISSUE TITLE
multivariate vs multivariable 😬

### ISSUE THREAD

**Issue by LucyMcGowan** [rstudio-education/datascience-box#58]
this is an awesome resource, thank you! I was looking through the data + vis slides and noticed there is a misuse of multivariate. This is sort of semantics, but I believe the line is actually referring to a **multivariable** data analysis (statistics has such annoying terminology because this obviously doesn't fit nicely with univariate / bivariate, but multivariate is actually referring to when there are multiple _outcomes_ not multiple variables). I'm happy to submit a PR, but wanted to check if there is a different wording that would be preferred.

> Multivariate data analysis - relationship between many variables at once, usually focusing on the relationship between two while conditioning for others

https://github.com/rstudio-education/datascience-box/blob/61fafe5d47132dedd9cee56fa07c116279545e18/slides/u1_d02-data-and-viz/u1_d02-data-and-viz.Rmd#L418

**Comment by mine-cetinkaya-rundel** [comment]
Hi @LucyMcGowan - thank you for the catch. A PR would be lovely!
