### ISSUE TITLE
Slides: footer often blocks the text

### ISSUE THREAD

**Issue by debbieyuster** [rstudio-education/datascience-box#77]
In several of the lecture slides, the footer covers up slide content, for example [this](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d02-meet-the-toolkit/u1_d02-meet-the-toolkit.html#33), [this](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d01-welcome/u1_d01-welcome.html#34), etc.

**Comment by debbieyuster** [comment]
Sorry, still having some trouble with the slide footer blocking slide content, as in [here](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d08-data-types/u1_d08-data-types.html#20).
For figures, I can just scale them down. But when it's actual code output that gets blocked, I'm not sure how to fix this - setting out.width in the code chunk headers didn't help in the above example.

**Comment by mine-cetinkaya-rundel** [comment]
Is making the code size smaller feasible? That's how I get around it sometimes, or making the text smaller, by placing them in 

```
.small[

]
```

**Comment by debbieyuster** [comment]
That worked - thanks!!
