### ISSUE TITLE
New CSS has caused some image sizes to be out of whack

### ISSUE THREAD

**Issue by debbieyuster** [rstudio-education/datascience-box#79]
A few days ago the slides were reknit with new CSS, which caused some image sizes to be off, for example [here](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d02-meet-the-toolkit/u1_d02-meet-the-toolkit.html#29). (I stuck with the old CSS so am not having this issue personally, but wanted to give a heads up.)

**Comment by mine-cetinkaya-rundel** [comment]
Ah ok, I'll fix them shortly.
