### ISSUE TITLE
Identifiers for course materials

### ISSUE THREAD

**Issue by dhicks** [rstudio-education/datascience-box#86]
Thanks very much for developing these materials.  This is a suggestion for improved usability.  

In the [schedule](https://datasciencebox.org/schedule.html), course materials are identified by unit, type, and title, eg, "Nobel laureates" is a lab in unit 1.  In the GitHub repository, course materials are organized by type and identified numerically, eg, "lab-03."  Finding the lab materials from the schedule requires navigating to a different part of the course website or hunting through the repository.  A column in the schedule with the numerical identifiers would be very convenient.

**Comment by mine-cetinkaya-rundel** [comment]
That's definitely a good idea, I'll try to get to it soon. If you'd like to start a PR with what you might have already mapped, happy to work off of that too.

**Comment by mine-cetinkaya-rundel** [comment]
I neglected to close this earlier, but this should be all In place now!
