### ISSUE TITLE
Link to merge conflict activity

### ISSUE THREAD

**Issue by debbieyuster** [rstudio-education/datascience-box#89]
The [Version Control](https://datasciencebox.org/version-control.html) section mentions an available merge conflict activity ("A sample activity for resolving merge conflicts is provided in the course materials."). I can't seem to find this, is it possible to link it? Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
It's here: 

https://github.com/rstudio-education/datascience-box/blob/4baa9159c3aa4984bff2fc06dae4776abf8f4057/course-materials/lab-instructions/lab-06/lab-06-ugly-charts.Rmd#L51-L79

But you're absolutely right that that's really buried. I could take it out of the lab or at least link to it from the description. Do you have a preference? (From semester to semester it changes whether I do this in lab or workshop depending on time...)

**Comment by debbieyuster** [comment]
Ah thanks! I think either is fine and a link would be easier.
