### ISSUE TITLE
Schedule tweak - Lab 06

### ISSUE THREAD

**Issue by debbieyuster** [rstudio-education/datascience-box#91]
The material in Lab 06 is covered in the slide decks: improving the faculty employment trends plot is in [Unit 1 Deck 7](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d07-tidy-data/u1_d07-tidy-data.html#4), and improving the fisheries plots is in [Unit 1 Deck 6](https://rstudio-education.github.io/datascience-box/course-materials/slides/u1_d06-data-join/u1_d06-data-join.html#12). So in the [Schedule](https://datasciencebox.org/schedule.html), I'd suggest replacing Lab 06 with something else - perhaps Part 2 of the LaQuinta/Denny's activity? (This should work out well for me, as I bumped the Traffic Accidents hw to Week 3 already).

**Comment by debbieyuster** [comment]
@mine-cetinkaya-rundel 
Another schedule-related issue: In both the 11- and 15-week schedules, the DC Bike Rentals HW is assigned in the same week as linear regression. This is the week before backward selection, a requirement of the bike share HW. Which could make sense if the HW timeframe is more than a week, but I still don't think it really fits *in* that week, and some of us have a shorter timeframe for HW assignments. I'd suggest, for the 15-week schedule:

- Change Week 9 HW from DC Bikes to GSS (I don't see why not? Looks like all the prereqs are covered.)
- Put DC Bike HW into Week 10 (which currently has no HW)
- As a result, Week 12 HW will need to be eliminated

**Comment by mine-cetinkaya-rundel** [comment]
I'm about to update all materials, and will keep this in mind for that restructuring as opposed to move things around for the current version. Thanks for pointing it out!
